// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportAccountApi.Models;

namespace SportAccountApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220625103809_CreateInitial")]
    partial class CreateInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");

                    b.HasData(
                        new
                        {
                            GroupsId = 1,
                            UsersId = 2
                        },
                        new
                        {
                            GroupsId = 1,
                            UsersId = 3
                        },
                        new
                        {
                            GroupsId = 2,
                            UsersId = 4
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GR-1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "GR-2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "GR-3"
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 982885884,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Number = 982881234,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Number = 982348884,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Number = 982685784,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Number = 982834884,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Client"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coach"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("AreaSize")
                        .HasColumnType("smallint");

                    b.Property<short>("Floor")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaSize = (short)20,
                            Floor = (short)2,
                            Name = "Large Dance Room",
                            Number = 201
                        },
                        new
                        {
                            Id = 2,
                            AreaSize = (short)10,
                            Floor = (short)2,
                            Name = "Middle Fitness Room",
                            Number = 205
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.ScheduleWorkday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("ScheduleWorkdays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachId = 1,
                            Date = new DateTime(2022, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2022, 6, 18, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 6, 18, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CoachId = 6,
                            Date = new DateTime(2022, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2022, 6, 18, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 6, 18, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.ScheduleWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SheduleWorkdayId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SheduleWorkdayId");

                    b.HasIndex("WorkoutTypeId");

                    b.ToTable("ScheduleWorkouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            RoomId = 1,
                            SheduleWorkdayId = 1,
                            WorkoutTypeId = 1,
                            end = new DateTime(2022, 6, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            start = new DateTime(2022, 6, 18, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            RoomId = 1,
                            SheduleWorkdayId = 1,
                            WorkoutTypeId = 2,
                            end = new DateTime(2022, 6, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            start = new DateTime(2022, 6, 18, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.Sex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sexs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Individual training"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yoga"
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main coach",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coach",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Senior gym coach",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Manager",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Head manager of the hall",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SexId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("SexId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("StatusId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2001, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeka",
                            LastName = "LN",
                            Login = "coach1",
                            MiddleName = "MN",
                            PasswordHash = new byte[] { 49, 247, 72, 141, 239, 252, 192, 211, 79, 244, 47, 104, 185, 146, 58, 10, 31, 47, 191, 31, 146, 248, 45, 137, 157, 239, 2, 235, 206, 116, 111, 196, 124, 117, 21, 217, 217, 169, 135, 172, 18, 74, 37, 68, 163, 58, 130, 241, 172, 124, 226, 232, 145, 33, 109, 100, 21, 181, 115, 115, 178, 185, 214, 11 },
                            PasswordSalt = new byte[] { 121, 141, 165, 241, 63, 174, 145, 150, 30, 112, 188, 47, 162, 90, 199, 91, 104, 29, 203, 219, 134, 203, 234, 177, 138, 107, 162, 8, 55, 36, 117, 186, 210, 106, 179, 20, 26, 96, 61, 45, 129, 14, 77, 138, 131, 71, 32, 169, 77, 189, 29, 146, 45, 150, 207, 120, 5, 201, 155, 57, 171, 19, 210, 11, 11, 89, 121, 97, 225, 233, 42, 210, 235, 9, 218, 65, 163, 36, 169, 206, 67, 21, 51, 95, 120, 39, 116, 82, 47, 223, 200, 190, 124, 155, 253, 212, 191, 55, 244, 100, 18, 223, 165, 43, 176, 21, 11, 15, 226, 221, 98, 142, 255, 110, 173, 127, 252, 77, 74, 150, 201, 216, 76, 185, 206, 248, 163, 82 },
                            RoleId = 2,
                            SexId = 1,
                            SpecializationId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2001, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rose",
                            LastName = "Menders",
                            Login = "client1",
                            PasswordHash = new byte[] { 49, 247, 72, 141, 239, 252, 192, 211, 79, 244, 47, 104, 185, 146, 58, 10, 31, 47, 191, 31, 146, 248, 45, 137, 157, 239, 2, 235, 206, 116, 111, 196, 124, 117, 21, 217, 217, 169, 135, 172, 18, 74, 37, 68, 163, 58, 130, 241, 172, 124, 226, 232, 145, 33, 109, 100, 21, 181, 115, 115, 178, 185, 214, 11 },
                            PasswordSalt = new byte[] { 121, 141, 165, 241, 63, 174, 145, 150, 30, 112, 188, 47, 162, 90, 199, 91, 104, 29, 203, 219, 134, 203, 234, 177, 138, 107, 162, 8, 55, 36, 117, 186, 210, 106, 179, 20, 26, 96, 61, 45, 129, 14, 77, 138, 131, 71, 32, 169, 77, 189, 29, 146, 45, 150, 207, 120, 5, 201, 155, 57, 171, 19, 210, 11, 11, 89, 121, 97, 225, 233, 42, 210, 235, 9, 218, 65, 163, 36, 169, 206, 67, 21, 51, 95, 120, 39, 116, 82, 47, 223, 200, 190, 124, 155, 253, 212, 191, 55, 244, 100, 18, 223, 165, 43, 176, 21, 11, 15, 226, 221, 98, 142, 255, 110, 173, 127, 252, 77, 74, 150, 201, 216, 76, 185, 206, 248, 163, 82 },
                            RoleId = 1,
                            SexId = 2
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1995, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mike",
                            LastName = "Clark",
                            Login = "client2",
                            PasswordHash = new byte[] { 49, 247, 72, 141, 239, 252, 192, 211, 79, 244, 47, 104, 185, 146, 58, 10, 31, 47, 191, 31, 146, 248, 45, 137, 157, 239, 2, 235, 206, 116, 111, 196, 124, 117, 21, 217, 217, 169, 135, 172, 18, 74, 37, 68, 163, 58, 130, 241, 172, 124, 226, 232, 145, 33, 109, 100, 21, 181, 115, 115, 178, 185, 214, 11 },
                            PasswordSalt = new byte[] { 121, 141, 165, 241, 63, 174, 145, 150, 30, 112, 188, 47, 162, 90, 199, 91, 104, 29, 203, 219, 134, 203, 234, 177, 138, 107, 162, 8, 55, 36, 117, 186, 210, 106, 179, 20, 26, 96, 61, 45, 129, 14, 77, 138, 131, 71, 32, 169, 77, 189, 29, 146, 45, 150, 207, 120, 5, 201, 155, 57, 171, 19, 210, 11, 11, 89, 121, 97, 225, 233, 42, 210, 235, 9, 218, 65, 163, 36, 169, 206, 67, 21, 51, 95, 120, 39, 116, 82, 47, 223, 200, 190, 124, 155, 253, 212, 191, 55, 244, 100, 18, 223, 165, 43, 176, 21, 11, 15, 226, 221, 98, 142, 255, 110, 173, 127, 252, 77, 74, 150, 201, 216, 76, 185, 206, 248, 163, 82 },
                            RoleId = 1,
                            SexId = 1
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1995, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jackson",
                            LastName = "Sweem",
                            Login = "client3",
                            PasswordHash = new byte[] { 49, 247, 72, 141, 239, 252, 192, 211, 79, 244, 47, 104, 185, 146, 58, 10, 31, 47, 191, 31, 146, 248, 45, 137, 157, 239, 2, 235, 206, 116, 111, 196, 124, 117, 21, 217, 217, 169, 135, 172, 18, 74, 37, 68, 163, 58, 130, 241, 172, 124, 226, 232, 145, 33, 109, 100, 21, 181, 115, 115, 178, 185, 214, 11 },
                            PasswordSalt = new byte[] { 121, 141, 165, 241, 63, 174, 145, 150, 30, 112, 188, 47, 162, 90, 199, 91, 104, 29, 203, 219, 134, 203, 234, 177, 138, 107, 162, 8, 55, 36, 117, 186, 210, 106, 179, 20, 26, 96, 61, 45, 129, 14, 77, 138, 131, 71, 32, 169, 77, 189, 29, 146, 45, 150, 207, 120, 5, 201, 155, 57, 171, 19, 210, 11, 11, 89, 121, 97, 225, 233, 42, 210, 235, 9, 218, 65, 163, 36, 169, 206, 67, 21, 51, 95, 120, 39, 116, 82, 47, 223, 200, 190, 124, 155, 253, 212, 191, 55, 244, 100, 18, 223, 165, 43, 176, 21, 11, 15, 226, 221, 98, 142, 255, 110, 173, 127, 252, 77, 74, 150, 201, 216, 76, 185, 206, 248, 163, 82 },
                            RoleId = 1,
                            SexId = 1
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1980, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Cook",
                            Login = "admin",
                            PasswordHash = new byte[] { 49, 247, 72, 141, 239, 252, 192, 211, 79, 244, 47, 104, 185, 146, 58, 10, 31, 47, 191, 31, 146, 248, 45, 137, 157, 239, 2, 235, 206, 116, 111, 196, 124, 117, 21, 217, 217, 169, 135, 172, 18, 74, 37, 68, 163, 58, 130, 241, 172, 124, 226, 232, 145, 33, 109, 100, 21, 181, 115, 115, 178, 185, 214, 11 },
                            PasswordSalt = new byte[] { 121, 141, 165, 241, 63, 174, 145, 150, 30, 112, 188, 47, 162, 90, 199, 91, 104, 29, 203, 219, 134, 203, 234, 177, 138, 107, 162, 8, 55, 36, 117, 186, 210, 106, 179, 20, 26, 96, 61, 45, 129, 14, 77, 138, 131, 71, 32, 169, 77, 189, 29, 146, 45, 150, 207, 120, 5, 201, 155, 57, 171, 19, 210, 11, 11, 89, 121, 97, 225, 233, 42, 210, 235, 9, 218, 65, 163, 36, 169, 206, 67, 21, 51, 95, 120, 39, 116, 82, 47, 223, 200, 190, 124, 155, 253, 212, 191, 55, 244, 100, 18, 223, 165, 43, 176, 21, 11, 15, 226, 221, 98, 142, 255, 110, 173, 127, 252, 77, 74, 150, 201, 216, 76, 185, 206, 248, 163, 82 },
                            RoleId = 3,
                            SexId = 1
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1990, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            LastName = "DL",
                            Login = "coach2",
                            MiddleName = "DN",
                            PasswordHash = new byte[] { 49, 247, 72, 141, 239, 252, 192, 211, 79, 244, 47, 104, 185, 146, 58, 10, 31, 47, 191, 31, 146, 248, 45, 137, 157, 239, 2, 235, 206, 116, 111, 196, 124, 117, 21, 217, 217, 169, 135, 172, 18, 74, 37, 68, 163, 58, 130, 241, 172, 124, 226, 232, 145, 33, 109, 100, 21, 181, 115, 115, 178, 185, 214, 11 },
                            PasswordSalt = new byte[] { 121, 141, 165, 241, 63, 174, 145, 150, 30, 112, 188, 47, 162, 90, 199, 91, 104, 29, 203, 219, 134, 203, 234, 177, 138, 107, 162, 8, 55, 36, 117, 186, 210, 106, 179, 20, 26, 96, 61, 45, 129, 14, 77, 138, 131, 71, 32, 169, 77, 189, 29, 146, 45, 150, 207, 120, 5, 201, 155, 57, 171, 19, 210, 11, 11, 89, 121, 97, 225, 233, 42, 210, 235, 9, 218, 65, 163, 36, 169, 206, 67, 21, 51, 95, 120, 39, 116, 82, 47, 223, 200, 190, 124, 155, 253, 212, 191, 55, 244, 100, 18, 223, 165, 43, 176, 21, 11, 15, 226, 221, 98, 142, 255, 110, 173, 127, 252, 77, 74, 150, 201, 216, 76, 185, 206, 248, 163, 82 },
                            RoleId = 2,
                            SexId = 1,
                            SpecializationId = 1,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models.WorkoutType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Group Type"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal Type"
                        });
                });

            modelBuilder.Entity("SportAccountApi.Models._RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expired_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("SportAccountApi.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportAccountApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportAccountApi.Models.Phone", b =>
                {
                    b.HasOne("SportAccountApi.Models.User", "User")
                        .WithMany("Phones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportAccountApi.Models.ScheduleWorkday", b =>
                {
                    b.HasOne("SportAccountApi.Models.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("SportAccountApi.Models.ScheduleWorkout", b =>
                {
                    b.HasOne("SportAccountApi.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("SportAccountApi.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("SportAccountApi.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportAccountApi.Models.ScheduleWorkday", "SheduleWorkday")
                        .WithMany()
                        .HasForeignKey("SheduleWorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportAccountApi.Models.WorkoutType", "WorkoutType")
                        .WithMany()
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Group");

                    b.Navigation("Room");

                    b.Navigation("SheduleWorkday");

                    b.Navigation("WorkoutType");
                });

            modelBuilder.Entity("SportAccountApi.Models.Status", b =>
                {
                    b.HasOne("SportAccountApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SportAccountApi.Models.User", b =>
                {
                    b.HasOne("SportAccountApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportAccountApi.Models.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportAccountApi.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId");

                    b.HasOne("SportAccountApi.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Role");

                    b.Navigation("Sex");

                    b.Navigation("Specialization");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SportAccountApi.Models._RefreshToken", b =>
                {
                    b.HasOne("SportAccountApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportAccountApi.Models.User", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
